version: "3.1"

services:
  mongodb:
    image: mongo:4
    restart: always
    user: ${UID}:${GID}
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./db:/data/db
    ports:
      - 127.0.0.1:27017:27017
    networks:
      - qmul

networks:
  qmul:
